application: dagensordibekk
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.txt)
  static_files: static/\1
  upload: static/(.*\.txt)
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /img
  static_dir: static/images

- url: /admin/.*
  script: main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /ord/cron/.*
  script: main.py
  login: admin

- url: .*
  script: main.py
  
  

